- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Install systemd-timesyncd
  package:
    name: systemd-timesyncd
  when: not ((ansible_distribution == 'Debian' and ansible_distribution_major_version is version('11', '<')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version('20', '<')) or ansible_distribution == 'Archlinux')

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started

- name: Run timedatectl
  command: timedatectl set-ntp true
